name: flutter_pdfview
description: A Flutter plugin that provides a PDFView widget on Android and iOS.
version: 1.2.5
homepage: https://github.com/endigo/flutter_pdfview

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.endigo.plugins.pdfviewflutter
        pluginClass: PDFViewFlutterPlugin
      ios:
        pluginClass: FLTPDFViewFlutterPlugin
